services:
  api:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      - mysql-db
      - redis
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-db/algorithm_db
      - REDIS_URL=redis://redis:6379/0
      - ALGO_BACKEND_URL=https://algo.inspectra.site  # Ensures API Hub can reach Algorithm Backend
      - RESOURCE_BACKEND_URL=https://storage.inspectra.site

    networks:
      - app_network

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: algorithm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
