version: '3.8'

services:
  api:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-db/algorithm_db
      - REDIS_URL=redis://redis:6379/0
      - ALGO_BACKEND_URL=https://algo.inspectra.site
      - RESOURCE_BACKEND_URL=https://storage.inspectra.site
    networks:
      - app_network

networks:
  app_network:
    external: true
