services:
  api:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      mysql-db:
        condition: service_healthy  
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@mysql-db/algorithm_db
      - ALGO_BACKEND_URL=https://algo.inspectra.site  # Ensures API Hub can reach Algorithm Backend
      - RESOURCE_BACKEND_URL=https://storage.inspectra.site
      - AUTH_SERVICE_URL=https://auth.inspectra.site
    networks:
      - app_network
    restart: always

  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: algorithm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_network
    volumes:
      - mysql_data:/var/lib/mysql  # Store MySQL data persistently
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge